# Dpo Detection Tool script :
***

In [1]:
import pandas as pd
import os 
from collections import Counter
import torch
path_work = "/media/concha-eloko/Linux/depolymerase_building"
#path_work = "/home/conchae/PhageDepo_pdb"

from transformers import AutoModelForTokenClassification, AutoTokenizer

model_path = f"{path_work}/esm2_t12_35M_UR50D-finetuned-depolymerase/checkpoint-198/"
#model_path = "/home/conchae/PhageDepo_pdb/script_files/esm2_t30_150M_UR50D-finetuned-depolymerase/checkpoint-198"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForTokenClassification.from_pretrained(model_path)

/home/concha-eloko/.local/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of the model checkpoint at /media/concha-eloko/Linux/depolymerase_building/esm2_t12_35M_UR50D-finetuned-depolymerase/checkpoint-198/ were not used when initializing EsmForTokenClassification: ['esm.contact_head.regression.weight', 'esm.contact_head.regression.bias']
- This IS expected if you are initializing EsmForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing EsmForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenc

In [32]:
# Encode input text
input_text = "MTTYKTGNPLGSAAVKDLFDNAENLDHFENDRSNETWENRFGVPGKTRYGMEQEHDRQISSQEARFQQFLLSSGYVFLGDYQDGPFQFGARNQYIRYDNQYYRLNAATDVGFTTTGTDATSFANDVTHFVLMDGDTLRQNLSSGDGFKWVGQVSSAAALSALPGSEGDRVLLLGYQDGWAATNSDLSGGGEFHYVSSLASVNNGVTVFNGWVRKFTRSVITTFDAGLSPGEDTDHFPQIQKLLEVVPDGFTVEIHGEHRLSSQLIMEVKRNITIVGVAAKLTTKPYKSTIKVVRLASDGITYMGGILSAINCPGLRLDGDLEIEGTRMYPNVLRSDQTAAGEEHGLHFRYCDDLYIGKDIYVHDVFGYGALGVYCNRAFAYRSMLTDTVRESGLNLFGGSVGGRAVGVRTRRTALYGVEIEDTWYGGARDIKVTNCDVEDAFWGIPTINNCSDVEVSGCNIRRARFGAQALQSSAGAYDTRNIRYHDNTYTGCPVGFRTAHPRNVRITRENIDQSEVMPYGYTYPFNNLLFVDNTDRRIFWGPTSSRFLTMVGQTIYIDDVAYTITAAATDATKTGYWKDFATDPDSLVKVTLDKVLPENTDIQTVKSKDWGTAVRGMLTEGRSVNLTIWNNDLTGDSLDSIGIYHNSYNMDGVNTVNESIRGNTFRAHGIWLRMNDAVNTRDVSDNKYADGSQIGISAANLTAAVLSQIKMGNNIRVALPARTSVAAGAVTKYFHANQRYWAVGLRISFTGLSGTGEMRVAIDGTQTHSATSYSTGTAVVEIYGVATFTKGNHQIAINTANSDIVFTSCDIELLIP"  # Replace this with your input text
input_ids = tokenizer.encode(input_text, return_tensors='pt', truncation= True)

# Get token classifications
with torch.no_grad() :
    outputs = model(input_ids)
    
logits = outputs.logits
probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
labels = model.config.id2label
tokens = []
token_probs, token_ids = torch.max(probs, dim=-1)
#for token_id, token_probs in zip(input_ids[0], probs[0]):
#    top_label_id = token_probs.argmax().item()
#    tokens.append(int(labels[top_label_id].split("_")[1]))
    
token_ids

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1

In [31]:
logits

tensor([[[ 1.1605, -0.2644, -0.5807],
         [ 1.4988, -0.5955, -0.8199],
         [ 1.8725, -0.6285, -0.9200],
         ...,
         [ 1.7728, -0.5479, -1.0512],
         [ 1.6444, -0.4632, -1.0848],
         [ 1.4983, -0.4026, -0.7848]]])

In [29]:
len(pad_or_truncate(tokens))

1500

In [19]:
logits.shape

torch.Size([819, 3])

In [16]:
import torch.nn.functional as F

def pad_or_truncate(self, tensor, max_len):
    if tensor.size(1) < max_len:
        tensor = F.pad(tensor, (0, 0, 0, max_len - tensor.size(1)))
    elif tensor.size(1) > max_len:
        tensor = tensor[:, :max_len, :]
    return tensor


tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
def make_prediction(fasta_txt) :
    if len(fasta_txt) > 200 :
        input_ids = tokenizer.encode(input_text, return_tensors='pt')
        outputs = model(input_ids)
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
        labels = model.config.id2label
        tokens = []
        for token_id, token_probs in zip(input_ids[0], probs[0]):
            top_label_id = token_probs.argmax().item()
            tokens.append(labels[top_label_id].split("_")[1])
        return tokens

for multifasta in os.listdir(path_fasta) :
    if multifasta[-5:] == "fasta" :
        fastas = SeqIO.parse(f"{path_fasta}/{multifasta}" , "fasta")
        for record in fastas :
            locus_tag = record.description.split("locus_tag=")[1].split("]")[0]
            annotation = "_".join(record.description.split("protein=")[1].split("]")[0].split())
            sequence = record.seq
            results = make_prediction(sequence)
            if "1" in dict(Counter(tokens)) :
                n_depo = dict(Counter(tokens))["1"]
            elif "2" in dict(Counter(tokens)) :
                n_depo = dict(Counter(tokens))["1"]
            else : 
                n_depo = 0
            with open(f"{path_bea_out}/{locus_tag}.{annotation}__{n_depo}.out" , "w") as outfile :
                outfile.write(str(results))

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

tokens = np.array(tokens)  # convert your list to numpy array for convenience

# create your plot
plt.figure(figsize=(10,6))

# plot data
for i in range(len(tokens) - 1):
    if tokens[i] == 0:
        color = 'black'
    elif tokens[i] == 1:
        color = 'blue'
    else:
        color = 'red'
        #tokens[i] == 1
    plt.plot([i, i+1], [tokens[i], tokens[i+1]], color=color, marker='o')

plt.xlabel('Token')
plt.ylabel('Label')
plt.title('Label for each token')
plt.xticks(rotation='vertical')
plt.yticks(np.arange(2), ['0', '1'])  
plt.grid(True)
plt.show()

In [ ]:
class Dpo_classifier(nn.Module):  # We define a new class Dpo_classifier which inherits from nn.Module. 
                                  # nn.Module is the base class for all neural network modules in PyTorch.

    def __init__(self, pretrained_model, num_classes):  # This is the constructor of the class. 
                                                         # When we create a new object of this class, 
                                                         # we have to provide a pretrained_model and the number of classes in the dataset.

        super(Dpo_classifier, self).__init__()  # This calls the constructor of the base class nn.Module.

        self.max_length = 1024  # Maximum length of the sequence. Any sequence longer than this will be truncated, and any shorter sequence will be padded.

        self.pretrained_model = pretrained_model  # We store the pretrained_model in an instance variable.

        self.rnn = nn.LSTM(input_size=num_classes, hidden_size=128, num_layers=1, batch_first=True)  # We create an LSTM layer.
                                                                                                     # input_size is the number of expected features in the input x.
                                                                                                     # hidden_size is the number of features in the hidden state h.
                                                                                                     # num_layers is the number of recurrent layers.

        self.classifier = nn.Linear(128, 2)  # We create a Linear layer.
                                              # This layer multiplies its input with its weight (a matrix) and then adds a bias (a vector).
                                              # The output size is 2, corresponding to two classes for binary classification.

    def preprocess_sequence(self, fasta_txt):  # Method to preprocess a sequence.
        encoded_input = tokenizer(fasta_txt, truncation=True, padding='max_length', max_length=self.max_length, return_tensors='pt')  # We tokenize the sequence.
                                                                                                                                    # truncation=True means that the sequence will be truncated to the maximum length if it's longer.
                                                                                                                                    # padding='max_length' means that the sequence will be padded to the maximum length if it's shorter.
                                                                                                                                    # return_tensors='pt' means that the tokens will be returned as PyTorch tensors.
        return encoded_input['input_ids']  # We return only the input_ids. These are the tokenized sequences, where each token has been replaced by its ID in the tokenizer vocabulary.

    def pad_or_truncate(self, tensor, max_len):  # Method to pad or truncate a tensor.
        if tensor.size(1) < max_len:  # If the second dimension of the tensor (sequence length) is less than max_len,
            tensor = F.pad(tensor, (0, 0, 0, max_len - tensor.size(1)))  # we pad the tensor on the second dimension. The padding value is 0.
        elif tensor.size(1) > max_len:  # If the second dimension of the tensor is greater than max_len,
            tensor = tensor[:, :max_len, :]  # we truncate the tensor on the second dimension.
        return tensor  # We return the padded or truncated tensor.

    def forward(self, sequences):  # Method to compute the forward pass of the model.
        inputs = self.preprocess_sequence(sequences)  # We preprocess the sequences.

        logits = self.pretrained_model(inputs).logits  # We pass the preprocessed sequences to the pretrained model and get the logits.

        logits = self.pad_or_truncate(logits, self.max_length)  # We pad or truncate the logits to have the same length for all sequences.

        _, (hidden_state, _) = self.rnn(logits)  # We pass the logits to the LSTM layer and get the hidden state. The output of the LSTM is not used.

        out = self.classifier(hidden_state.squeeze(0))  # We pass the hidden state to the Linear layer and get the output of the model.

        return out  # We return the output of the model.
